version: '3.8'

include:
  - "./infra.yaml"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVICE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      DB_TIMEOUT: ${DB_TIMEOUT}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      DB_MAX_POOL_CON: ${DB_MAX_POOL_CON}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}
      REDIS_PORT: ${REDIS_PORT}
      CONTAINER_NAME: ${SERVICE_CONTAINER_NAME}
      SERVICE_PORT: ${SERVICE_PORT}
    depends_on:
      - database
      - cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - ${SERVICE_PORT}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    deploy:
      resources:
        limits:
          memory: 1.5G

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
