version: '3.8'

services:
  database:
    image: postgres:13
    container_name: ${DB_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6
    container_name: ${CACHE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      REDIS_DB: ${REDIS_DB}
    expose:
      - ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
