version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: user_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0:5432" # This will dynamically allocate a host port for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: user_redis
    env_file:
      - .env
    ports:
      - "0:6379" # This will dynamically allocate a host port for Redis
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
