version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0:5432" # This will dynamically allocate a host port for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: ${REDIS_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - "0:6379" # This will dynamically allocate a host port for Redis
    volumes:
      - redis_data:/data

  user_service:
    build:
      context: .
    container_name: ${USER_SERVICE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_DB: ${REDIS_DB}
      CONTAINER_NAME: ${USER_SERVICE_CONTAINER_NAME}
      INTERNAL_PORT: 50051
    ports:
      - "0:50051" # This will dynamically allocate a host port for the gRPC service
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
