version: '3.8'

services:
  postgresql:
    image: postgres:14
    container_name: ${DB_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5384
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5384
    ports:
      - "5384:5384"
    volumes:
      - location_postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=5384"]
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: ${CACHE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      REDIS_DB: ${REDIS_DB}
    expose:
      - 6236
    ports:
      - "6236:6236"
    volumes:
      - location_redis_data:/data
    command: ["redis-server", "--port", "6236"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVICE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      DB_TIMEOUT: ${DB_TIMEOUT}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      DB_MAX_POOL_CON: ${DB_MAX_POOL_CON}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}
      REDIS_PORT: ${REDIS_PORT}
      CONTAINER_NAME: ${SERVICE_CONTAINER_NAME}
      SERVICE_PORT: ${SERVICE_PORT}
    depends_on:
      - postgresql
      - redis
    ports:
      - "5050:5050"
    expose:
      - 5050
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  location_postgres_data:
  location_redis_data:
