version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: ${CACHE_CONTAINER_NAME}
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ftgo_gateway_redis_data:/data
    command: ["redis-server", "--port", "${REDIS_PORT}"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVICE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DEBUG: ${DEBUG}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DB: ${REDIS_DB}
      REDIS_PORT: ${REDIS_PORT}
      SERVICE_PORT: ${SERVICE_PORT}
    depends_on:
      - redis
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ftgo_gateway_redis_data:
