version: "3.8"

services:
  message_broker:
    image: 'rabbitmq:3.9-management'
    container_name: message_broker
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network

volumes:
  rabbitmq_data:

networks:
  backend_network:
    external: true
