version: '3.8'

services:
  gateway_redis:
    image: redis:6.2-alpine
    restart: always
    container_name: "gateway_redis"
    hostname: "gateway_redis"
    environment:
      - REDIS_HOST=gateway_redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "6490:6379"
    volumes:
      - gateway_redis_data:/data
    networks:
      - backend-network

  user_postgresql:
    image: postgres:14
    container_name: "user_postgresql"
    hostname: "user_postgresql"
    environment:
      - POSTGRES_HOST=user_postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=user_database
    ports:
      - "5438:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  user_redis:
    image: redis:6.2-alpine
    restart: always
    container_name: "user_redis"
    hostname: "user_redis"
    ports:
      - "6235:6379"
    environment:
      - REDIS_HOST=user_redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - user_redis_data:/data
    networks:
      - backend-network
  message_broker:
    image: 'rabbitmq:3.9-management'
    container_name: "message_broker"
    hostname: "rabbitmq"
    restart: always
    environment:
      - ENVIRONMENT=test
      - DEBUG=true
      - RABBITMQ_USER=rabbitmq_user
      - RABBITMQ_PASS=rabbitmq_password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=/
      - RABBITMQ_SSL_CONNECTION=false
    ports:
      - "15920:15672"
      - "5920:5672"
    volumes:
      - message_broker_data:/var/lib/rabbitmq
    networks:
      - backend-network
volumes:
  gateway_redis_data:
  user_postgres_data:
  user_redis_data:
  message_broker_data:

networks:
  backend-network:
    external: true
